### ISSUE TITLE
Empty inbox page

### ISSUE THREAD

**Issue by hanxue** [asm-helpful/helpful-web#345]
I am running Helpful on a local vagrant box. Signing up and logging in works, but when I look at the Inbox page, this is what I see:

![image](https://cloud.githubusercontent.com/assets/760008/7015670/d3f4c3f6-dd09-11e4-9a4a-96469875f588.png)

I have tried loading the page on Chrome, Firefox and Safari with the same results. I don't see any errors in the log files. Am I missing a step?

**Comment by ramdyne** [comment]
I had the same. Clicking around, everything else seems to work, but there's no way to view the three unread messages. Viewing the inbox results in an empty screen as mentioned by hanxue.

**Comment by lachlanjc** [comment]
@hanxue @ramdyne Hey guys, could you please use the Assembly chat for getting help? On Assembly products, GitHub is only for hosting the code and managing PRs. Here's the Helpful chat (just ping someone on @core): https://assembly.com/chat/helpful

Thanks!

**Comment by hanxue** [comment]
Alright, will head over to Assembly. Can I suggest adding a `Support` section in README to redirect people so they know where to get help? Most of us will open a new Github Issue by default when we face a problem or have feature requests etc :smiley:

**Comment by hanxue** [comment]
I will keep this issue open. Convenient to post log output, as well as linked to pull requests and commits that will eventually solve the problem. 

Once I have gotten over the hurdle of doorkeeper in #344 , I see these errors in the worker log

```
$ tail -f /var/log/helpful.log/worker-1.log 
TID-otrbh4zsk ERROR: Error fetching message: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq.rb:74:in `redis'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/fetch.rb:102:in `retrieve_work'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/fetch.rb:37:in `block in fetch'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/util.rb:16:in `watchdog'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/fetch.rb:33:in `fetch'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/fetch.rb:44:in `block (2 levels) in fetch'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
TID-otrbh4zsk ERROR: /opt/ruby/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
TID-otrcakmug INFO: Terminating 5 quiet workers
```

Redis is up and running in the Vagrant box though

**Comment by hanxue** [comment]
This is the HTML body for a Helpful account at helpful.io

```
<div class="container">

    ::before
    <div classname="row">
        <div classname="col-md-8 col-md-offset-2">
            <div data-react-props="{"accountSlug":"hanxue","archived":false}" data-react-class="ConversationList">
                <div class="list list-conversations" data-reactid=".0">
                    <div class="conversation is-collapsed" data-reactid=".0.$91d03230-6df7-4fad-8ae8-38e20377cbe2">
                        <div data-reactid=".0.$91d03230-6df7-4fad-8ae8-38e20377cbe2.0">
                            <div class="conversation-header" data-reactid=".0.$91d03230-6df7-4fad-8ae8-38e20377cbe2.0.0">
                                <div class="status status-info" data-reactid=".0.$91d03230-6df7-4fad-8ae8-38e20377cbe2.0.0.0"></div>
```

On my local deployment, the same Inbox page request generate this:

```
<div class="container">

    ::before
    <div classname="row">
        <div classname="col-md-8 col-md-offset-2">
            <div data-react-props="{"accountSlug":"leehanxue","archived":false}" data-react-class="ConversationList">
                <div data-reactid=".0"></div>
            </div>
```

After `data-reactid`, none of the messages got displayed. When I check in Firefox's Inspector, the server did respond properly to `conversation.json` with JSON messages

![screen shot 2015-04-10 at 11 59 37 am](https://cloud.githubusercontent.com/assets/760008/7081725/9a020272-df79-11e4-85e1-c1d88315c0e2.png)
